### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by jmrtns** [peer/mind#1]
Some managers are very likely to use their manager account password for everything and if they sign into coucil site their manager accout could be compromised

**Comment by mitar** [comment]
Yea. :-)

**Comment by jmrtns** [comment]
Should we just buy a SSL authentication or should we just use self authentication?

**Comment by mitar** [comment]
We can get them for free at [StartSSL](https://www.startssl.com/).

**Comment by mitar** [comment]
Self authentication is not secure for this purpose.

**Comment by derbear** [comment]
not as bad as it could be given that http://workshift.bsc.coop has no SSL

but yeah, this is a good thing to fix

**Comment by mitar** [comment]
I worry about how this will be maintained in the future. We are not the best at things which have to be done regularly at more than yearly interval.

There is a new project which is aiming to fix that, [Let's encrypt](https://letsencrypt.org/). So let's maybe wait for them to make it public.

**Comment by mitar** [comment]
Done using Let's encrypt [and this Docker image](https://github.com/tozd/docker-nginx-proxy) which will make sure certificates are kept up to date in the future as well.

**Comment by mitar** [comment]
See it in action: https://council.cloyne.org/
