### ISSUE TITLE
Implement Flexbox-like grid system for responsive design

### ISSUE THREAD

**Issue by chilldude** [peer/mind#133]
Here is a cool framework to look at: http://bulma.io/ which is a flexbox css framework. we can implement a grid system like that

any other ideas?

**Comment by mitar** [comment]
What, GitHub supports multiple people to be assigned! Whoa!

**Comment by chilldude** [comment]
how did you not know this haha

**Comment by mitar** [comment]
I think it is [new](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests). :-)

**Comment by mitar** [comment]
OK, back to the topic. I am not sure that we need another framework? I am OK using flex (I think I use it in few cases already), but swapping or adding the whole framework at the moment – I do not think we have resources for that.

I also do not see why this framework adds so much more in comparison with others.

So I would be more against it for now.

**Comment by chilldude** [comment]
okay, i see materializecss offers a grid too..i did not know that before.
we can use their grid system to make it responsive then for later #65

**Comment by mitar** [comment]
Yes. So materialize already has responsive design. If you go and make window smaller, it will change the header and menu. I made that. I didn't have time for the rest.

Not sure why it does not work in your development view though. But with window changes it does.

I will close this ticket then for now.
