### ISSUE TITLE
Notifications on discussions you've been active in

### ISSUE THREAD

**Issue by joshl129** [peer/mind#156]
I am loving the new platform! One feature I would be interested in, however, is email notifications for new activity on discussions. I'm not sure how difficult it is to program something like this, but it would be really helpful in keeping afloat of discussions with new comments, motions, and perhaps points. 

Perhaps, to keep our inboxes from exploding with contentious discussions, these notifications could be such that you would receive only one notification for all new activity; this is to be contrasted with individual notifications for every new comment, motion, and point. Furthermore, you would only receive notifications for discussions you yourself participate in: if you're not too interested in a discussion and for that reason don't contribute anything except for perhaps a vote on motions, you wouldn't receive notifications. And each user would be able to disable all notifications, or perhaps even customize them to their own liking.

**Comment by mitar** [comment]
Thank you for your great interest in this app! I really appreciate you opening issues here. To keep issues organized, I have to organize them a bit. In this particular case, there were already few issues talking about notifications, so I will be closing this issue in favor of existing ones. This does not mean that your ideas are not valuable and I will definitelly keep them in mind. Feel free to also read other issues and add your thoughts there.

See: #112 #78 #2
