### ISSUE TITLE
Push past discussions up to the current week's list of discussions if no motion has passed

### ISSUE THREAD

**Issue by joshl129** [peer/mind#159]
This would be helpful in allowing members to easily see which discussions are still open for voting, even if those motions are from previous weeks. I imagine it would be easy to code, since you'd just push the discussions with the status "Voting Open" to the top. 

Perhaps this would be useful also for ongoing discussions without motions (maybe the House Presidents can pin these so that they, too, get pushed to the top of the discussions page). 

Alternatively, perhaps it would be easy to implement a tab (near the tabs "Discussions", "Meetings", and the tab for one's own account/settings) with "Open discussions" (or perhaps "Voting/Discussion in Progress"); this could be contrasted with the current "Discussions" tab by renaming that to "All Discussions".

**Comment by joshl129** [comment]
Examples are all the election pages

**Comment by mitar** [comment]
Let's have this discussion after I finish the current iteration of changes to the list of discussions.

**Comment by mitar** [comment]
See how it is now.

**Comment by joshl129** [comment]
I like the toggle, with the default view just showing discussions that are
open or to be voted on. Thanks for the prompt change, Mitar!

**Comment by mitar** [comment]
OK, I will be then closing this. I am also thinking about adding a badge on each discussion where you still have to vote.
