### ISSUE TITLE
Activity feed

### ISSUE THREAD

**Issue by joshl129** [peer/mind#163]
Some activity feeds that I like are the ones for Facebook and for Google Drive (perhaps these could serve as models for building PeerMind's).

In my opinion, only new discussions, new comments, new motions, and decisions (hereafter altogether called "happenings") should appear on the activity feed (thumbs-up and points would not). 

Perhaps the default view would be of just new happenings since you last logged on, with the option to see all happenings (_ad initio_). 

I feel that this would be helpful because, when I go to PeerMind, all I usually want to see are these happenings, and the only way to do so currently is to manually look at each discussion or through the list of current discussions.

Like Facebook and Google Drive, happenings in the activity feed would be hyperlinked for convenience (e.g., to the discussion that is new, that has been decided, or that has other new happenings). 

They would also include other relevant information, like the poster's name (if applicable), date and time posted or decided, etc.

**Comment by mitar** [comment]
Yes, this is definitely needed. It is just quite some work to do to support something like that. But yes, we should have it!

**Comment by mitar** [comment]
Done.
