### ISSUE TITLE
Fix clahub link or clarify contribution policy

### ISSUE THREAD

**Issue by nealmcb** [peer/mind#202]
I'm told that in order to contribute to this repo I need to sign the Contributor License Agreement. But
the link at https://github.com/peer/mind/blob/master/CONTRIBUTING.md to https://www.clahub.com/agreements/peer/mind gives me an error:
> The page you were looking for doesn't exist.  You may have mistyped the address or the page may have moved.

**Comment by mitar** [comment]
Yea, something is wrong here. :-) It seems there is also clahub bot which is failing for us at the moment. Will have to look into this.

**Comment by mitar** [comment]
BTW, how are you told that you have to sign the agreement? Because normally a GitHub webhook show that but at the moment is not working. (I am investigating why.) So do you know that you should sign it from CONTRIBUTING.md?

**Comment by mitar** [comment]
For now you can try signing the agreement at this old link: https://www.clahub.com/agreements/mitar/mind

**Comment by nealmcb** [comment]
I saw some sort of text that noted I'd need to read some contribution agreement information, and I think I went looking for it and found CONTRIBUTING.md.

I tried using that old clahub link.  I agreed to the conditions, authenticated with Github, and then got
> We're sorry, but something went wrong.

**Comment by mitar** [comment]
Thanks for trying. I reported the issue upstream: https://github.com/clahub/clahub/issues/154

**Comment by mitar** [comment]
I gave up on CLA. I think I will just go with DCO for now.
