### ISSUE TITLE
For/Against Points Formatting

### ISSUE THREAD

**Issue by mkanwal** [peer/mind#29]
Could we have it so that these points could also be formatted?

(At the very least, I would like to be able to put line breaks by pressing 'Enter' and have that formatting retained after submitting the point)

**Comment by mitar** [comment]
Hm, I wanted that to be as concise as possible. so that we do not get essays there. So that they are really one line. Can you give me an example where are lines needed? Instead of just making multiple points?

**Comment by mkanwal** [comment]
I agree, but I think that's why only moderators have the privilege to post those.

Example is http://council.cloyne.org/discussion/LNgjxoRhmeEodQiFN

I wanted to write:

Two options:
1. Graham's...
2. Bryan's thing...

I can imagine important hyperlinks/quotes etc being needed in the summarizing points sometimes.

**Comment by mitar** [comment]
Ah, for "other". Hm.
