### ISSUE TITLE
Document statistical quorum

### ISSUE THREAD

**Issue by mitar** [peer/mind#34]
It would be great to create documentation for statistical quorum. So, explanation with diagrams. Showing what exactly are the intervals we are computing for credibility and confidence (also  that it is clearer why they can be different), what is the hypothesis we are solving.

@mkanwal, can you make this into the document? LaTeX or something?

**Comment by mkanwal** [comment]
Will do.

**Comment by mitar** [comment]
Ping. :-)

**Comment by mkanwal** [comment]
yes, yes, in the Fall I will do it.
