### ISSUE TITLE
App Icons for Sandstorm Package

### ISSUE THREAD

**Issue by neynah** [peer/mind#41]
Hi @mitar! I'm happy to help out with designing an a set of icons for your app. Since you haven't yet decided on a name, maybe it would help for you to list about 10 words that describe your app/logo to help me come up with some concepts. [Here are some words that phildini chose for ContactOtter.](https://github.com/phildini/logtacts/issues/17#issuecomment-172638915)

If you already have a concept in mind, that's great too. :)

**Comment by mitar** [comment]
That's awesome. I do not have any idea yet. I am currently leaning towards a non-meaningful name (like "google").

About phrases (words are harder) I associate with the app: finding a common path, working together, collaboration, voting, constructive discussions, listening to each other, finding what is important and what is not, moving forward, community, respect, ideas, knowledge, reconciliation.

Color scheme is also not yet decided on (for the whole app). I am currently just using default colors from http://materializecss.com/, so this red/green combination, but I would probably be changing this. So probably logo will then inform also the color scheme.

Maybe @wrought and @mkanwal can help as well with some brainstorming.

**Comment by mitar** [comment]
@wrought put some ideas for a name into #35 as well.

**Comment by mkanwal** [comment]
Berkeley color scheme since that is where it's being used (for now)...?
http://www.berkeley.edu/brand/img/colors/Brandcolors.jpg

A non-meaningful name might be good, since it's too difficult to pin what we're try to achieve with this down to a word.  "Google" is actually meaningful in a peripheral way (it refers to "googol"); it's sort of 1 or 2 degrees separated from a literal description of what it is.

"Consensus"?  That would embody what we _want_ its usage to help make happen :)

**Comment by mitar** [comment]
> Berkeley color scheme since that is where it's being used (for now)...?

Don't even think!

> "Consensus"? That would embody what we want its usage to help make happen :)

I am adding the word to the list above. But I think there were too many apps with that name already. :-)

**Comment by mitar** [comment]
@subjective, maybe you could help with name as well. :-)

**Comment by mitar** [comment]
So we have a ticket #35 where people are brainstorming names.

[This ticket](https://github.com/mitar/council-app/issues/35#issuecomment-211911235) has an image attached to it. I like it, but not sure if logo like that would work.

**Comment by neynah** [comment]
@mitar I do like the people in a circle concept. I think it's workable should you decide that's the direction you'd like to go. Abstract versions of that (e.g. a ring with circles around it, etc.) would also work well as a logo. I'll start some sketches once there's consensus / you decide on it.

**Comment by neynah** [comment]
Hi @mitar are there new logo ideas for PeerMind yet? I can work on it this week. :)

**Comment by mitar** [comment]
That would be great! Not many ideas, but some things I would like to convey is that people come together to make a decision, find a common path, people discussing. I am not completely sure if we should really try to have people in the logo, because this would make it too detailed, but maybe some abstraction of them. Circle is also good. Maybe circles in general (if we see circles as their positions, and then through discussion you find common ground, an intersection).

**Comment by neynah** [comment]
Alright, here's what I've come up with:
- I went with fun, inviting colours
- The outside circles darken inside the inner circle to show that they're engaging in the middle (like a discussion)
![image](https://cloud.githubusercontent.com/assets/855341/14972243/f1c0038c-108e-11e6-969a-05e5f16d3a75.png)

**Comment by mitar** [comment]
> I went with fun, inviting colours

I like that! :-) (Although, they look to me still a bit neutral, but this is also good.) Colors are good.

> The outside circles darken inside the inner circle to show that they're engaging in the middle 

Hm, but smaller circles do not touch, so they are engaging, but they do not reach each other? So here is the idea that you get to common decision, decide together something.

But I like eve as it is as well. Maybe juts without an explicit inner circle:

![52f6c064-108f-11e6-9db0-ed8dc7b7bc95](https://cloud.githubusercontent.com/assets/585279/14973043/312f9f1a-1098-11e6-83cd-51f509c11dc5.png)

In this way your have three people who are engaging themselves and finding out the hidden common thing (the circle we can feel, but not yet observe). :-) Maybe.

**Comment by neynah** [comment]
I like both! :D Let me know if you like the version without the middle circle as the final design. I can create the icon set.

**Comment by mitar** [comment]
Let's wait a day or two for others to give some input. But I would go with one without the middle circle otherwise.

**Comment by mkanwal** [comment]
Nice ideas!  I like hiding the inner circle.  

Could we compare side-by-side the one posted above w/o inner circle, with one that has all three intersect at a point (also w/o inner circle)?  The mixing of colors in the latter might be nice, showing the various mutual agreements between each circle.

**Comment by neynah** [comment]
@mkanwal Do you mean intersecting & overlapping?
![image](https://cloud.githubusercontent.com/assets/855341/14994256/baf40480-1123-11e6-8ec5-2f882839e1fe.png)

**Comment by mkanwal** [comment]
Hmm, yeah, maybe too much going on in the triple intersection one.

I like the one on the left more.

**Comment by mitar** [comment]
@neynah: I agree with @mkanwal, the right one looks too crowded. Can you just try one more: what if circles would be touching, just barely. Like three heads which are leaning on each together. And then an implicit inner circle is being created as we have it now?

**Comment by neynah** [comment]
Like so?
![image](https://cloud.githubusercontent.com/assets/855341/14999142/2f637b26-113c-11e6-9ece-a36897278bea.png)

**Comment by neynah** [comment]
The one on the right feels a little too cluttered to me. (I would personally go with the one on the left, or something in between the two where the circles are not quite touching but still close to each other)

**Comment by mitar** [comment]
Hm, I still think left is better. We might need some personal space between people making decisions. :-) And I also like that the left circle is much larger than any individual.

OK, then let's go with the left one. With existing distances between circles. Let's make this a final design. Thanks @neynah!

Can you then go and make the icon set, and also a vector version of the logo?

What are the details of the copyright here? Our plan is to have all the non-code content be under CC-BY-SA license, with attribution to this project. Would that be OK with you? We can list you as a contributor somewhere of course (we do not yet have a page). Maybe the easiest would be if you create a pull request adding those files to a directory in this repository. Then you would be among contributors on GitHub.

**Comment by neynah** [comment]
@mitar Sounds great, I'll create a PR with the files & get back to you shortly about the copyright details.

**Comment by mitar** [comment]
Icons does not seem to be rendered correctly in Inkscape and Gimp. :-(

**Comment by mitar** [comment]
Fixed with #138.
