### ISSUE TITLE
Add responsive design

### ISSUE THREAD

**Issue by jwentwistle** [peer/mind#65]
The comments and motions should stack when views on smaller devices.

**Comment by mitar** [comment]
I was thinking of using tabs in that case.

**Comment by jwentwistle** [comment]
Ohhh, that's a good idea. However, I think there should be either chat or comments next to the motions. And I'm not sure how the _points_ differ from the comments with a vote on them.

**Comment by mitar** [comment]
So the main view which has to become responsive is the discussion view. What I imagined there is that it switches to the view where you have three tabs for each column, and on the top you can switch between them (so maybe always on tabs header, or something like that if you scroll up, tabs headers appear, but if you scroll down they hide). The idea is that you can smoothly swipe left and right to convert between those modes. I do not think there is a way to really show both motions and discussions at the same time. Also, this is a normal progression of the discussion: you have comments, then you get summaries into points, and then you make a decision.
