### ISSUE TITLE
Add cloyne.cloaca e-mail as an account

### ISSUE THREAD

**Issue by jmrtns** [peer/mind#8]
We should add cloyne.cloaca so people can bring up anonymous discussions and make anonymous comments

**Comment by mitar** [comment]
Then it is easier to just allow non-signed-in users to do that?

**Comment by mitar** [comment]
But how could they edit their discussions? I think a better solution should be made here. So for now maybe they can do that through managers (so managers help them put it online). But later on we could have some way to get anonymous accounts and allow them to edit their content.

Or we could just allow registration of new accounts? They could comment and open discussions and motions, but not vote.

**Comment by jmrtns** [comment]
I don't know this seem more like something to discuss with presidents and possibly council

**Comment by mitar** [comment]
Closing in favor of #157 which has much more substantial discussion on how to allow anonymous posts.
