### ISSUE TITLE
Allow @mentioning people in comments and elsewhere

### ISSUE THREAD

**Issue by mitar** [peer/mind#84]
Related to #78, but #78 is more about subscribing people to notifications, while this ticket is more about support for `@mention` syntax inside the text. The #78 could be done through some other means, like some other form to get people to be subscribed. Or we might just support `@mention` everywhere in rich-text content and then based on the context where this editor is, people would be also subscribed to notifications.

**Comment by mitar** [comment]
Depends on: https://github.com/basecamp/trix/issues/284

**Comment by mitar** [comment]
Explanation how to do it: https://github.com/basecamp/trix/issues/270

**Comment by mitar** [comment]
Useful: https://github.com/ichord/At.js

**Comment by mitar** [comment]
And: https://github.com/selectize/selectize.js

**Comment by bhushangaykawad** [comment]
> Useful: https://github.com/ichord/At.js

How to use this ? I couldn’t find any solution please help

**Comment by mitar** [comment]
We do not use any of those libraries at the end.

**Comment by bhushangaykawad** [comment]
i want to use @mitar mentions in trix.. i couldn’t find any example with vue . Can you plz guide me !

**Comment by mitar** [comment]
I cannot. This project is not using Vue.

**Comment by bhushangaykawad** [comment]
Just give me example code how to get mentions in trix and i’ll make it a vue component on my own.

**Comment by mitar** [comment]
See it in the commit referenced above.
